name: modelmaker
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.4
  - asttokens=2.4.1
  - bzip2=1.0.8
  - ca-certificates=2024.8.30
  - comm=0.2.2
  - debugpy=1.8.6
  - decorator=5.1.1
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - importlib-metadata=8.5.0
  - ipykernel=6.29.5
  - ipython=8.18.1
  - jedi=0.19.1
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - krb5=1.21.3
  - libcxx=19.1.0
  - libedit=3.1.20191231
  - libffi=3.4.2
  - libsodium=1.0.20
  - libsqlite=3.46.1
  - libzlib=1.3.1
  - matplotlib-inline=0.1.7
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - openssl=3.3.2
  - packaging=24.1
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=24.2
  - platformdirs=4.3.6
  - prompt-toolkit=3.0.48
  - psutil=6.0.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.18.0
  - python=3.9.20
  - python_abi=3.9
  - pyzmq=26.2.0
  - readline=8.2
  - six=1.16.0
  - stack_data=0.6.2
  - tk=8.6.13
  - tornado=6.4.1
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - wcwidth=0.2.13
  - wheel=0.44.0
  - xz=5.2.6
  - zeromq=4.3.5
  - zipp=3.20.2
  - pip:
      - aiohappyeyeballs==2.4.3
      - aiohttp==3.10.8
      - aiosignal==1.3.1
      - annotated-types==0.7.0
      - anyio==4.6.0
      - astroid==3.2.4
      - async-timeout==4.0.3
      - attrs==24.2.0
      - black==24.8.0
      - certifi==2024.8.30
      - cfgv==3.4.0
      - charset-normalizer==3.3.2
      - click==8.1.7
      - cmdstanpy==1.2.4
      - contourpy==1.3.0
      - cycler==0.12.1
      - cython==3.0.11
      - dill==0.3.9
      - distlib==0.3.8
      - filelock==3.16.1
      - fonttools==4.54.1
      - frozenlist==1.4.1
      - fsspec==2024.9.0
      - holidays==0.57
      - identify==2.6.1
      - idna==3.10
      - importlib-resources==6.4.5
      - isort==5.13.2
      - jinja2==3.1.4
      - joblib==1.4.2
      - kiwisolver==1.4.7
      - markupsafe==2.1.5
      - matplotlib==3.9.2
      - mccabe==0.7.0
      - mpmath==1.3.0
      - multidict==6.1.0
      - mypy-extensions==1.0.0
      - networkx==3.2.1
      - nodeenv==1.9.1
      - numpy==1.24.3
      - pandas==2.2.3
      - pathspec==0.12.1
      - patsy==0.5.6
      - pillow==10.4.0
      - pipdeptree==2.23.4
      - plotly==5.24.0
      - pre-commit==3.8.0
      - prophet==1.1.5
      - pydantic==2.9.2
      - pydantic-core==2.23.4
      - pylint==3.2.7
      - pyparsing==3.1.4
      - pystan==2.19.1.1
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - pytz==2024.2
      - pyyaml==6.0.2
      - requests==2.32.3
      - schedule==1.2.2
      - scikit-learn==1.5.1
      - scipy==1.13.1
      - seaborn==0.13.2
      - setuptools==72.1.0
      - sniffio==1.3.1
      - stanio==0.5.1
      - starlette==0.38.5
      - statsmodels==0.14.2
      - sympy==1.13.3
      - tenacity==9.0.0
      - threadpoolctl==3.5.0
      - tomli==2.0.1
      - tomlkit==0.13.2
      - torch==2.4.1
      - tqdm==4.66.5
      - tzdata==2024.2
      - urllib3==2.2.3
      - virtualenv==20.26.6
      - xgboost==2.1.1
      - yarl==1.13.1
